Django-Flashcards-Web-App/accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

Django-Flashcards-Web-App/flashcard_project/urls.py
# This file serves the purpose to route urls to views

from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import admin
from . import views # . means we are in the same directory (views is in same directory as urls)

# r - raw text
# ^ - start at this string
urlpatterns = [ 

    # Index url - Maps an empty url string such as 'localhost:8000' to the home function in views.py
    url(r'^$', views.index, name = 'index'), 
    url(r'^admin/', admin.site.urls), 
    url(r'^flashcards/', include(('flashcards.urls', 'flashcards'), namespace = 'flashcards')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Django-Flashcards-Web-App/flashcards/urls.py
# flashcards app urls conf
from django.conf.urls import url
from . import views # . means we are in the same directory (views is in same directory as urls)

urlpatterns = [ 
    url(r'^$', views.flashcards, name = 'flashcards'), 
    url(r'create/', views.create_card_set, name = 'create_card_set'), 
    url(r'create_card/(?P<card_set_id>[\d]+)', views.create_card, name = 'create_card'), 
    url(r'delete/(?P<card_set_id>[\d]+)', views.delete_card_set, name = 'delete_card_set'), 
    url(r'delete_card/(?P<card_id>[\d]+)', views.delete_card, name = 'delete_card'), 
    url(r'edit/(?P<card_set_id>[\d]+)', views.edit_card_set, name = 'edit_card_set'),
    url(r'edit_card/(?P<card_id>[\d]+)', views.edit_card, name = 'edit_card'), 
    url(r'view/(?P<card_set_id>[\d]+)', views.view_card_set, name = 'view_card_set'), 
    url(r'dictionary/', views.dictionary, name = 'dictionary'),
]

Django-Flashcards-Web-App/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
        crossorigin="anonymous">

        <meta name="viewport" content="width-device-width, initial-scale=1.0">

        {% block head %}
        <div class="container">
            <title>Django Flashcards</title>
        </div>
        {% endblock %}

    </head>

    <br>

    <body>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'index' %}">Django Flashcards</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'flashcards:flashcards' %}">Flashcards<span class="sr-only">(current)</span></a>
                    </li>

                    {% if request.user.is_superuser %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'admin:index' %}"><b>Admin Panel</b><span class="sr-only">(current)</span></a>
                    </li>    
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        Hi {{ user.username }}!
                        <a href="{% url 'logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a href="{% url 'login' %}">Log In</a>
                    </li>
                    {% endif %}
                </ul>

                <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'flashcards:dictionary' %}">
                    <input class="form-control mr-sm-2" 
                    name="word_searched" value="{{request.GET.word_searched}}" 
                    placeholder="Vocabulary Dictionary" aria-label="Search">
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
                </form>
              
            </div>
        </nav>
    

    <br>
    
    {% block body %}
    <div class="container">
        <h1>FlipIt</h1>
    </div>
    {% endblock %}

    </body>

    <script
    src="http://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>

    <script 
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
    crossorigin="anonymous"></script>

</html>

Django-Flashcards-Web-App/templates/home.html
{% extends 'base.html' %}

{% block head %}
<title>Django Flashcards | Home</title>
<head>
<meta name='viewport' content='width=device-width, initial-scale=1'>
<script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
{% endblock %}

{% block body%}
<div class="container">

    <!--The <i> tag is a smily face :)-->
    <h3>Welcome to Django Flashcards <i class='far fa-grin' style='font-size:24px'>
    </i></h3>

      
        <a class="btn btn-link" href="{% url 'flashcards:flashcards' %}" role="button">
        <h5><b>Flashcards</b></h5></a>

</div>
{% endblock %}