Django-Flashcards-Web-App/accounts/urls.py
# accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

Django-Flashcards-Web-App/flashcard_project/urls.py
# This file serves the purpose to route urls to views

from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import admin
from . import views # . means we are in the same directory (views is in same directory as urls)

# r - raw text
# ^ - start at this string
urlpatterns = [ 

    # Index url - Maps an empty url string such as 'localhost:8000' to the home function in views.py
    url(r'^$', views.index, name = 'index'), 
    url(r'^admin/', admin.site.urls), 
    url(r'^flashcards/', include(('flashcards.urls', 'flashcards'), namespace = 'flashcards')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Django-Flashcards-Web-App/flashcards/urls.py
# flashcards app urls conf
from django.conf.urls import url
from . import views # . means we are in the same directory (views is in same directory as urls)

urlpatterns = [ 
    url(r'^$', views.flashcards, name = 'flashcards'), 
    url(r'create/', views.create_card_set, name = 'create_card_set'), 
    url(r'create_card/(?P<card_set_id>[\d]+)', views.create_card, name = 'create_card'), 
    url(r'delete/(?P<card_set_id>[\d]+)', views.delete_card_set, name = 'delete_card_set'), 
    url(r'delete_card/(?P<card_id>[\d]+)', views.delete_card, name = 'delete_card'), 
    url(r'edit/(?P<card_set_id>[\d]+)', views.edit_card_set, name = 'edit_card_set'),
    url(r'edit_card/(?P<card_id>[\d]+)', views.edit_card, name = 'edit_card'), 
    url(r'view/(?P<card_set_id>[\d]+)', views.view_card_set, name = 'view_card_set'), 
    url(r'dictionary/', views.dictionary, name = 'dictionary'),
]

Django-Flashcards-Web-App/flashcards/models.py
import random
from django.db import models

# Models for the 'flashcards' app
class Card_Set(models.Model):
    '''
    Card_Set model functions as the deck that a card belongs to
    A deck has a topic and description
    '''
    topic = models.CharField(max_length = 50, null = False, blank = False)       # Topic of the Deck
    description = models.CharField(max_length = 300, null = False, blank = True) # Description of topic
    created_by = models.CharField(max_length= 300, null = False, blank = True)
    is_active = models.BooleanField(default = True)   # When Card_Set is created, it will default to
                                                      # being inactive as no cards will exist in the set
    # __str__ is a function that modifies string representation
    # When Cards.objects.all() is run, the name of the word will be displayed
    # Without this function, Cards.objects.all() would return [<Cards: Cards object (1)>]
    def __str__(self):
        return self.topic


    def get_card_count(self):
        '''
        Returns the card count in each deck as an integer
        '''
        return self.card_set.count()
    get_card_count.short_description = 'Card Count'  # Card Count is the column header in Admin Panel


    def get_random_card(self):
        '''
        Returns a random card from the deck
        '''
        random_number = random.randint(0, self.card_set.count() - 1)    # Return random card from deck
        random_card = self.card_set.all()[random_number]
        return random_card


class Card(models.Model):
    '''
    Card model for the cards in the deck
    Parent is the Card_Set model
    Each card has word, definition, and sentence
    '''
    parent_card_set = models.ForeignKey(Card_Set, on_delete = models.CASCADE)

    word = models.CharField(max_length = 50, null = False, blank = False)         # Vocabulary word
    definition = models.TextField(max_length = 500, null = False, blank = False)  # Word's definition
    sentences = models.TextField(max_length = 500, null = False, blank = True)    # Word used in sentence


    def __str__(self):
        return self.word


    def is_there_previous_card(self):
        '''
        Returns True if card is not the frist card in the deck
        '''
        first_card_in_set = self.parent_card_set.card_set.first()
        if self == first_card_in_set:
            return False
        else:
            return True


    def get_previous_card(self):
        '''
        Returns the previous card in the deck
        '''
        first_card_in_set = self.parent_card_set.card_set.first()

        if self == first_card_in_set:
            return self.parent_card_set.card_set.last()
        else:
            return self.parent_card_set.card_set.filter(id__lt = self.id).last()


    def is_there_a_next_card(self):
        '''
        Returns True if the card is not last in the deck
        '''
        last_card_in_set = self.parent_card_set.card_set.last()
        if self == last_card_in_set:
            return False
        else:
            return True


    def get_next_card(self):
        '''
        Returns the next card in the deck
        '''
        last_card_in_set = self.parent_card_set.card_set.last()
        if self == last_card_in_set:
            return self.parent_card_set.card_set.first()
        else:
            return self.parent_card_set.card_set.filter(id__gt = self.id).first()

Django-Flashcards-Web-App/flashcards/forms.py
from django.forms import ModelForm
from django import forms
from .models import Card_Set, Card

class Card_Set_Form(ModelForm):
    '''
    Form mapping to the Card_Set model
    '''
    class Meta:
        model = Card_Set
        fields = ['topic', 'description', 'created_by']
        #fields = ['topic', 'description', 'is_active']



class Card_Form(ModelForm):
    '''
    Form mapping to the Card model
    '''
    class Meta:
        model = Card
        fields = ['parent_card_set', 'word', 'definition', 'sentences']

Django-Flashcards-Web-App/flashcards/views.py
# flashcards views
from django.shortcuts import (
    HttpResponseRedirect,
	get_object_or_404,
    render
)
from django.urls import reverse
from .models import Card_Set, Card
from .forms import Card_Set_Form, Card_Form
from PyDictionary import PyDictionary
# from django.contrib.auth.models import User


# Views for the 'flashcards' app
def flashcards(request):
    '''
    Renders the flashcard app's flashcards.html template
    '''
    # Card_Set.objects.all() returns all cards in the database
    topic_query_set = Card_Set.objects.all().order_by('topic').filter(is_active = True)
    context = {'topics': topic_query_set}   # Dictionary{} rendered for flashcards/flashcards.html
    return render(request, 'flashcards/flashcards.html', context)


def create_card_set(request):
    '''
    Renders a template used to create POST requests to create a new card set
    '''
    # Create the form instance and populate data from the request
    if request.method == 'POST':
        form = Card_Set_Form(request.POST)

        if form.is_valid():                                               # Check if form is valid
            form.save()                                                   # Save form - object saved to database
            return HttpResponseRedirect(reverse('flashcards:flashcards')) # Redirect to the flashcards view

    else:
        if request.user.is_authenticated:
            form = Card_Set_Form(initial={'created_by': request.user.get_username()})
        else:
            form = Card_Set_Form()

    context = {'form': form}
    return render(request, 'flashcards/create_card_set.html', context)


def create_card(request, card_set_id):
    '''
    View to create a new card in the given card set id
    '''
    # get_object_or_404() displays '404 error' if it fails to get object
    card_set_object = get_object_or_404(Card_Set, id = card_set_id)

    if request.method == 'POST':
        form = Card_Form(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('flashcards:flashcards'))

    else:
        form = Card_Form(initial = {'parent_card_set': card_set_object})

    context = {'form': form}
    return render(request, 'flashcards/add_edit_cards.html', context)


def delete_card(request, card_id):
    '''
    Deletes card whose id == card_id
    '''
    card_object = get_object_or_404(Card, id = card_id)
    card_object.delete()
    return HttpResponseRedirect(reverse('flashcards:flashcards'))


def delete_card_set(request, card_set_id):
	'''
	Deletes card set whose id == card_set_id
	'''
	card_set_object = get_object_or_404(Card_Set, id = card_set_id)
	card_set_object.delete()
	return HttpResponseRedirect(reverse('flashcards:flashcards'))


def edit_card(request, card_id):
    '''
    View that renders a form to edit the card object's information
    '''
    card_object = get_object_or_404(Card, id = card_id)

    if request.method == 'POST':
        form = Card_Form(request.POST, instance = card_object)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('flashcards:flashcards'))

    else:
        form = Card_Form(instance = card_object)

    context = {'form': form, 'edit_mode': True, 'card_object': card_object}
    return render(request, 'flashcards/add_edit_cards.html', context)


def edit_card_set(request, card_set_id):
	'''
	View that renders a form to edit the card set object's information
    '''

	card_set_object = get_object_or_404(Card_Set, id = card_set_id)

	if request.method == 'POST':
		form = Card_Set_Form(request.POST, instance = card_set_object)

		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse('flashcards:flashcards'))

	else:
		form = Card_Set_Form(instance = card_set_object)

	context = {'form': form, 'edit_mode': True, 'card_set_object': card_set_object}
	return render(request, 'flashcards/create_card_set.html', context)


def view_card_set(request, card_set_id):
    '''
    View to get card set from the database -
    returns the first card in card set -
    unless a card_id is defined in the url
    '''
    card_set_object = get_object_or_404(Card_Set, id = card_set_id)
    card_list = card_set_object.card_set.all()	# Returns all cards in respective card set
    card_object = card_list.first()			    # Returns the first card in the set

    # Condition to get the next/previous card in the set
    if request.method == 'GET' and 'card' in request.GET:
        card_object = get_object_or_404(Card, id = request.GET['card'])

    context = {'card_set_object': card_set_object, 'card_object': card_object}
    return render(request, 'flashcards/view_cards.html', context)


def dictionary(request):
    '''
    View for the 'search bar' in the
    navbar - a page is rendered that
    displays the searched word and its
    definition using PyDictionary
    '''

    try:
        if request.method == 'GET':
            word_searched = request.GET.get('word_searched')
            dictionary = PyDictionary()                  # PyDictionary module
            word_def = dictionary.meaning(word_searched) # Get definition of word searched
            word_def = list(word_def.values())[0][0]     # Extract definition as a string

    except:
        word_def = 'This word does not exist in the database'

    context = {'word_searched': word_searched, 'word_def': word_def}
    return render(request, 'flashcards/dictionary.html', context)

Django-Flashcards-Web-App/flashcards/templates/flashcards/add_edit_cards.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block head %}
{% if card_object %}
    <title>Card: {{ card_object | upper }}</title>
{% else %}
    <title>New Card</title>
{% endif %}
{% endblock %}

{% block body %}

<div class="container">
    <div class="col-xl-6">
        
        {% if card_object %}
            <h3>Card: {{ card_object | upper}}</h3>
            <h6>Edit your card below</h6>
        {% else %}
            <h3>Add Card</h3>
            <h6>Create a new card below</h6>     
        {% endif %}
        
        <form method="POST" nonvalidate>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}
            
            <button class="btn btn-primary btn-md" type="submit">Save</button>

            {% if edit_mode %}
            <a class="btn btn-primary btn-md" 
            href="{% url 'flashcards:delete_card' card_object.id %}" 
            role="button">Delete {{ card_object | upper }}</a>
            {% endif %}
        </form>

    </div>
</div>
{% endblock %}

Django-Flashcards-Web-App/flashcards/templates/flashcards/create_card_set.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block head %}
<title>Create a Card Set</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="col-xl-6">
        <h3>Custom Card Set</h3>
        <h6>Create your custom study deck below!</h6>

        <form method="POST" nonvalidate>
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}

            <button type="submit" class="btn btn-primary btn-sm">Submit</button>

             {% if edit_mode %}
            <a class="btn btn-primary btn-sm" href="{% url 'flashcards:delete_card_set' card_set_object.id %}" 
            role="button">Delete</a>
            {% endif %}
        </form>
        
    </div>
</div>

{% endblock %}

Django-Flashcards-Web-App/flashcards/templates/flashcards/dictionary.html
{% extends 'base.html' %}

{% block head %}
<title>{{ word_searched }}</title>
{% endblock %}

{% block body%}

<!-- Display user search in the center of the page, 
     returning the searched word and its definition -->
<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <p><b>{{ word_searched }}</b>: {{ word_def }}</p>
    </div>
</div>

{% endblock %}


         

Django-Flashcards-Web-App/flashcards/templates/flashcards/flashcards.html
{% extends 'base.html' %}

{% block head %}
<title>Django Flashcards | Card Decks</title>
{% endblock %}

{% block body%}

    <div class="column ml-5">
        <h3>Custom Card Set</h3>
        <h6>Create a custom study set</h6>
        <p>
        <a class="btn btn-primary" href="{% url 'flashcards:create_card_set' %}"  
        role="button">Create New</a>
        </p>
    </div>

<div class="row">
{% for t in topics %}
{% cycle 'primary' 'warning' 'danger' 'secondary' 'success' 'info' 'dark' as color silent %}
    {% if forloop.counter0|divisibleby:3 %}
        </div><br><div class="row ml-5">
    {% endif %}

        <div class="column">

            {% if forloop.counter0 == 2 %}
            <div class="card text-white bg-{{ color }} mr-5" style="width: 17rem;">
            {% else %}
            <div class="card text-white bg-{{ color }} mr-3" style="width: 17rem;">
            {% endif %}

            <div class="card-header">{{ t.description }}
            </div>
            <div class="card-body">
                <h4 class="card-title">{{ t.topic}}</h4>
                <h6 class="card-text">Created By: {{t.created_by}}</h6>
                

                <!--conditional statement for plural/singular use of the word card displayed on template-->
                {% if t.get_card_count != 1 %}
                    <h6 class="card-subtitle mb-2 text-white">{{ t.get_card_count }} cards in deck</h6>
                {% else %}
                    <h6 class="card-subtitle mb-2 text-white">{{ t.get_card_count }} card in deck</h6>
                {% endif %}

                <!--p-- class="card-text">{{ t.description }}</!--p-->
                <a href= "{% url 'flashcards:view_card_set' t.id %}" class="card-link text-white">Study</a>
                <a href= "{% url 'flashcards:edit_card_set' t.id %}" class="card-link text-white">Edit Deck</a>
                <a href= "{% url 'flashcards:create_card' t.id %}" class="card-link text-white">Add Card</a>
            </div>
            </div>
        </div>
        
{% endfor %}
{% endblock %}

         

Django-Flashcards-Web-App/flashcards/templates/flashcards/view_cards.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block head %}
<title>Django Flashcards | Flashcards</title>

<head>
<style>
.flip-card {
	background-color: transparent;
	width: 500px;
	height: 300px;
	/*border: 1px solid #f1f1f1;*/
	perspective: 1000px; /* Remove this if you don't want the 3D effect */
}

/* This container is needed to position the front and back side */
.flip-card-inner {
	position: relative;
	width: 100%;
	height: 100%;
	text-align: center;
	transition: transform 0.8s;
	transform-style: preserve-3d;
}

/* Do an horizontal flip when you move the mouse over the flip box container */
.flip-card:hover .flip-card-inner {
	transform: rotateY(180deg);
}

/* Position the front and back side */
.flip-card-front, .flip-card-back {
	position: absolute;
	width: 100%;
	height: 100%;
	backface-visibility: hidden;
}

/* Style the front side (fallback if image is missing) */
.flip-card-front {
	background-color: #4d4dff;
	color: white;
}

/* Style the back side */
.flip-card-back {
	background-color: dodgerblue;
	color: white;
	transform: rotateY(180deg);
}

</style>
</head>
{% endblock %}

{% block body%}
<div class="container">
<div class="row">

	<div class="col-md-4 mr-5">
	{% if card_object %}
	<div class="flip-card">
	<div class="flip-card-inner">

		<!--Front of Card-->
		<div class="flip-card-front">
		<div class="card-header">{{ card_set_object }}
		</div>
		<p>
		<h4 class="card-title" style="font-size: 45px">{{ card_object.word }}</h4>
		</p>
		</div>

		<!--Back of Card-->
		<div class="flip-card-back">
		<p>
		<h4 class="card-text">{{ card_object.definition }}</h4>
		</p>
		</div>
	</div>
	</div>

	<br>
	{% else %}
	<p><b>No cards are in the {{card_set_object | upper }} card set.</b></p>
	{% endif %}
	
	<!--Previous/Random/Next Card Buttons-->
	<nav aria-label="...">
	<ul class="pagination pagination-lg">

		{% if card_object %}
		<li class="page-item"><a class="page-link" 
		href="{% url 'flashcards:view_card_set' card_set_object.id %}?card={{ card_object.get_previous_card.id }}">
		Previous</a></li>

		<li class="page-item"><a class="page-link"
		href="{% url 'flashcards:view_card_set' card_set_object.id %}?card={{ card_set_object.get_random_card.id }}">
		Random</a></li>

		<li class="page-item"><a class="page-link" 
		href="{% url 'flashcards:view_card_set' card_set_object.id %}?card={{ card_object.get_next_card.id }}">
		Next</a></li>
		{% endif %}
	</ul>
	</nav>
	
	
	<nav aria-label="...">
	<ul class="pagination pagination-lg">
	<li class="page-item"><a class="page-link" 
	href="{% url 'flashcards:edit_card_set' card_set_object.id %}"
	role="button">Edit Deck</a><p>

	{% if card_object %}
	<li class="page-item"><a class="page-link" 
	href="{% url 'flashcards:edit_card' card_object.id %}"  
	role="button">Edit Card</a><p>
	{% endif %}

	<li class="page-item"><a class="page-link"  
	href="{% url 'flashcards:create_card' card_set_object.id %}"  
	role="button">Add Card</a><p>
	</ul>
	</nav>
	</div>

	<div class="col-sm-2 mr-2">
		<p></p>
	</div>

	<div class="col-xl-4">
		<h6>Sentences for - {{ card_object.word | upper }}</h6>

		{% if card_object.sentences|length == 0 %}
			<p>You have not written a sentence for {{ card_object.word }}.</p> 
			<a class="btn btn-outline-warning" href="{% url 'flashcards:edit_card' card_object.id %}" role="button">
			Write a Sentence</a>
		{% else %}
			<p>{{ card_object.sentences }}</p>
			<a class="btn btn-outline-warning" href="{% url 'flashcards:edit_card' card_object.id %}" role="button">
			Edit Sentence</a>
		{% endif %}

	</div>
</div>
</div>
{% endblock %}